# Introduction to MATLAB

## The Basics
1. Getting started
2. Navigation with MATLAB
3. Data types
4. MATLAB as a calculator
5. Matrix operations
6. Loops and logical operations
7. Functions
8. Scripts

MATLAB is a high level mathematical programming language developed by Mathworks. It was originally intended to be a language that would enable the easy programming of matrix calculations and linear algebra. It now has much broader applications than this and is used widely in scientific research.

MATLAB has many in-built mathematical functions. It supports matrix manipulations, statistical analysis, optimisation, the plotting of graphs and figures. It can be used as a platform for running neural networks, quantitative models, machine learning and for conducting psychological experiments.

The overarching aim of this module is not to take you up to the level of an expert MATLAB programmer; instead, we will teach you some of the computational approaches that are applied in neuroscience research, including with examples where cutting edge approaches are applied to clinical data. We intend to provide you with enough programming knowledge to be able to apply these approaches for your own purposes with reference to this resource.

## Prerequisites
The aim of this tutorial will be to provide you with an introduction to the MATLAB commands in a Jupyter environment and to provide you with the basic knowledge of MATLAB programming that you will need in subsequent days. It is not necessary to have previous programming experience; everything that you need to know is in the tutorials. You can use the information in this tutorial as a reference. If you have programmed before then todays tutorial may seem quite basic. We will move on to more interesting work in the subsequent days.


### Entering simple commmands
First try entering a couple of simple mathematical commands to MATLAB. Type the yellow text into the command line panel and then press enter. (NB - code to try out will be shown in this same format throughout the tutorials).

In [6]:
10 * 8


ans =

    80



Now for somthing a little more interesting

In [7]:
for i = 1:10

i * 8

end


ans =

     8


ans =

    16


ans =

    24


ans =

    32


ans =

    40


ans =

    48


ans =

    56


ans =

    64


ans =

    72


ans =

    80



MATLAB has calculated i * 8  for each integer value from 1 to 10 in ascending order.

## Navigation with MATLAB

To navigate from the command line in MATLAB you use the change directory 'cd' command. Try to navigate to the following directory on your computer.

In [12]:
cd ~/DATA/Day1

This folder should contain the data for today's tutorial. To list the contents of the folder to the command line use the list 'ls' command or the directory 'dir' command. These are similar, but dir produces a more detailed output.

In [14]:
ls
dir

Functions  webdata


.          ..         .DS_Store  Functions  webdata    



You can also use ls or cd to either view, or move up or down a level in the directory structure

The '..' mean up one directory in the tree, whereas '.' means the current directory. E.g. try

In [15]:
ls webdata
ls .
ls ..

behavioural.mat

Functions  webdata

DataDay7  Day1	Day2  Day2_morning_scan_data  Day3  Day4  Day5	ToolBoxes



Navigate into the subfolder called 'webdata' and examine the contents using ls .

In [16]:
cd webdata
ls .

behavioural.mat



In [17]:
load behavioural.mat

In a MATLAB environment, you would see a whole set of variables appear in the workspace. Three of them starting with the prefix T*. These are measures from cognitive tests collected via the Internet. The others are from a questionnaire that the same individuals filled out. Examine some of them in the variables panel.

You can print the variables names to the command line.

In [19]:
who


Your variables are:

AGE                        RELIGIOSITY                
ALCOHOL_UNITS_PER_WEEK     SMOKE_PERDAY               
BRAINTRAINING_FREQUENCY    T1_SpatialMemory           
CAFFEINE                   T2_VisuospatialProcessing  
COMPUTER_GAMES_FREQUENCY   T3_VerbalReasoning         
EDUCATIONLEVEL             ans                        
EMPLOYMENT                 i                          
GENDER                     
HANDEDNESS                 



You also can print the variables values to the command line.

In [23]:
AGE % This will be a very long list

Error using eval
Undefined function or variable 'AGE'.



You can remove variables from the workspace using the 'clear' command. E.g., try clearing a specific variable.

In [21]:
clear AGE

## Saving data

Saving data is also simple. First, clear all variables using the 'clear' command. The workspace will now be empty. We will revisit the Internet dataset in more detail later in the day.

Now define two new variables: v1 and v2.

In [24]:
v1 = [1 2 3]


v1 =

     1     2     3



In [25]:
v2 = 'stringvariable'


v2 =

    'stringvariable'



These should now be visible in the workspace. You can call the variables via the command line.

In [26]:
v1


v1 =

     1     2     3



To save them use the 'save' command

In [27]:
save tmpdata

In [28]:
ls

behavioural.mat  tmpdata.mat



There is now a new mat file with the new variables stored in it. You can clear the workspace again using the 'clear' command safe in the knowledge that the variables that you created can be retrieved from the .mat file if they are required at a later time.

## Types of data

Data in MATLAB can be declared as variables in the form of numbers or strings and these can be arranged into arrays or matrices. Variables are fundamental to all programming; therefore, we will now look at some of the most common variable types.

### Number variables
You can declare a number variable as follows.

In [31]:
vara = 1


vara =

     1



It is possible to define multiple variables at the same time.

In [32]:
vara = 7; varb=3;

Using ';' suppresses MATLAB from outputting the variables to the command line. The code is still executed though and the number is added to the workspace. This is useful when running more complex code, othewise the output can be overly verbose. You can see the variables that are in the workspace via the Workspace panel. Additionally, you can output their names to the command line panel using the 'who' command.

In [33]:
who


Your variables are:

ALCOHOL_UNITS_PER_WEEK     T1_SpatialMemory           
BRAINTRAINING_FREQUENCY    T2_VisuospatialProcessing  
CAFFEINE                   T3_VerbalReasoning         
COMPUTER_GAMES_FREQUENCY   ans                        
EDUCATIONLEVEL             i                          
EMPLOYMENT                 v1                         
GENDER                     v2                         
HANDEDNESS                 vara                       
RELIGIOSITY                varb                       
SMOKE_PERDAY               



Typing the variable name will output its value to the comamnd line. Try the following commands.

In [34]:
vara
varb
vara + varb


vara =

     7


varb =

     3


ans =

    10



By default, MATLAB truncates numbers to four decimal places. You can change the number of decimal places using the 'format' command. Try typing in the following commands, which divide vara by varb.

In [35]:
vara / varb

format long;

vara / varb

format short e;

vara / varb

format bank;

vara / varb

format short;

vara / varb


ans =

    2.3333


ans =

   2.333333333333333


ans =

   2.3333e+00


ans =

          2.33


ans =

    2.3333



Numbers may also be rounded to integers using the int32 command.

In [36]:
int32(vara / varb)


ans =

  int32

   2



### Creating vectors
In MATLAB numbers are often stored as vectors or matrices. Vectors can be in vertical and horizontal orientations. You declare vectors using square brakets. Try the following

In [38]:
varc = [2 4 6]


varc =

     2     4     6



In [39]:
varc = [2; 4; 6]


varc =

     2
     4
     6



This produces vectors in horizontal and vertical orientations. You can transpose between these orientations.



In [40]:
varc = [2 4 6]
varc = varc'


varc =

     2     4     6


varc =

     2
     4
     6



Vectors can be added to each other or to individual numbers.



In [42]:
varc + vara
vard = [1; 2; 3]
varc + vard


ans =

     9
    11
    13


vard =

     1
     2
     3


ans =

     3
     6
     9



However, in order to add vectors they must have the same length.

In [44]:
vard = [1; 2; 3; 4]
varc + vard


vard =

     1
     2
     3
     4



Matrix dimensions must agree.



### Creating Matrices
Matrices are multidimensional arrays of numbers. They can also be defined using square brakets.



In [46]:
mata = [1 2 3;4 5 6]


mata =

     1     2     3
     4     5     6



In [47]:
mata'


ans =

     1     4
     2     5
     3     6



Try the following statements:



In [48]:
mata * 10


ans =

    10    20    30
    40    50    60



In [49]:
mata + 10



ans =

    11    12    13
    14    15    16



In [50]:
ones(2,4)


ans =

     1     1     1     1
     1     1     1     1



In [51]:
eye(4)


ans =

     1     0     0     0
     0     1     0     0
     0     0     1     0
     0     0     0     1



In [52]:
eye(9)


ans =

     1     0     0     0     0     0     0     0     0
     0     1     0     0     0     0     0     0     0
     0     0     1     0     0     0     0     0     0
     0     0     0     1     0     0     0     0     0
     0     0     0     0     1     0     0     0     0
     0     0     0     0     0     1     0     0     0
     0     0     0     0     0     0     1     0     0
     0     0     0     0     0     0     0     1     0
     0     0     0     0     0     0     0     0     1



Matrix and vector calculations will be covered in more detail later.



### Creating Strings
Text is stored and manipulated in string variables. When strings are defined they must be enclosed in apostrophe marks, i.e., 'STRING'. Try the following statement.



In [3]:
stringa = 'My String'


stringa =

    'My String'



You can use the 'whos' command to examine the properties of this new string variable.




In [4]:
whos

  Name         Size            Bytes  Class    Attributes

  stringa      1x9                18  char               



Here you can see that the string has 9 characters. Knowing a string's length can be very useful and is returned by the 'length' function.

In [5]:
length(stringa)


ans =

     9



You can extract a substring from a string by defining the index of the characters within curved brackets. Try the following commands.



In [6]:
stringa(1)
stringa(1:5)
stringa(1:2:9)


ans =

    'M'


ans =

    'My St'


ans =

    'M tig'



Strings can also be converted to numbers - for example, each character has a numerical 'ascii' code



In [7]:
asciistring = uint8(stringa)


asciistring =

  1x9 uint8 row vector

    77   121    32    83   116   114   105   110   103



They ascii codes can be converted back to text characters.



In [8]:
char(asciistring)


ans =

    'My String'



Multi-line strings also are possible, however, each line must be the same length.



In [9]:
stringb = ['a b c';'c d e']


stringb =

  2x5 char array

    'a b c'
    'c d e'



We will learn more about string operations as we go along in later tutorials. For now, the most important thing is to understand the distinction between String and Number variables in MATLAB.